### ISSUE TITLE
[ENHANCEMENT] Show the "Load" button/link on the initial screen

### ISSUE THREAD

**Issue by NintendoManiac64** [LostRuins/lite.koboldai.net#6] opened 2023-03-31 05:11 UTC
When you visit https://lite.koboldai.net (ideally test this in a private browsing window for a repeatable environment), the "Load" button/link is not shown until you first select something.

Thing is though, it would seem that you can load scenarios that are completely different than the existing/current scenario, implying that there's no need to first select the corresponding scenario (e.g. you can select the "Fantasy Isekai" adventure scenario and then load an "Emily" chat without issue).

So my enhancement suggestion is to show the "Load" button/link at the top next to the "Quick Start" button/link.

**Comment by LostRuins** [comment] 2023-04-07 05:32
So the issue is that - suppose you load a story from file, then what AI model will be used to generate the text? This can be determined when selecting a scenario, but there is no way to tell for a random user's story. So rather than randomly assign a model, it would be better for the user to pick a model first, and then allow the load, that way the user decides.

**Comment by NintendoManiac64** [comment] 2023-04-07 06:48
> This can be determined when selecting a scenario, but there is no way to tell for a random user's story

Then how is it that I can select the scenario "Fantasy Isekai" but then load a json file from an "Emily" chat without actually first selecting the "Emily" scenario?

**Comment by LostRuins** [comment] 2023-04-07 08:27
The scenario stores 3 things by default:
1. The prompt content itself
2. The settings to play (which mode to use chat/story/adventure etc)
3. Which list of models to use, selected from the active workers at that time

The json story on the other hand stores:
1. The prompt/story content itself
2. (optional) the user's last settings when playing the story

These 2 are not necessarily compatible, for example it is entirely possible for a story to not contain any settings at all. And even if it does, the model they previously selected may no longer exist on the horde. That's why directly loading a story without selecting a model is not a good idea.

**Comment by NintendoManiac64** [comment] 2023-04-07 20:40
> the model they previously selected may no longer exist on the horde

My previously-created "Dr. Katherine" json files were still successfully loading and generating seemingly in-character responses even when that scenario was removed during the last week or so.

**Comment by LostRuins** [comment] 2023-04-08 02:42
Yes, a specific scenario can work on multiple models. That scenario runs on the Pygmalion 6B model which is usually available, so it should work. But if loading is allowed on a general .json story then it would lead to poorer results as people load random stories but dont have a correct model to use them on.

**Comment by NintendoManiac64** [comment] 2023-04-08 02:46
And I'm guessing it'd be a non-starter to include information of the scenario within a JSON?

I mean, it could also be useful in general to not worry about having to keep track of what JSON files came from which scenario.

**Comment by LostRuins** [comment] 2023-04-08 03:14
@NintendoManiac64 there is also the issue that these files are supposed to be cross compatible with the official KoboldAI PC client, so I can't just randomly add or assume a specific new field will exist.

**Comment by LostRuins** [comment] 2023-12-24 15:30
Closing as outdated - current UI starts with a default set of models selected already, so load will be visible anyway.

**Closed by LostRuins** 2023-12-24 15:30 UTC
